name = "trns-pwa"
main = "src/index.js"
compatibility_date = "2025-08-01"
workers_dev = true
routes = [ { pattern = "trns.inpriv.xyz", custom_domain = true } ]
[assets]
directory = "./public"
binding = "ASSETS"
